# permissions for end users to view cortexes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: cortex-viewer-role
rules:
- apiGroups:
  - cortex.cortex.io
  resources:
  - cortexes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cortex.cortex.io
  resources:
  - cortexes/status
  verbs:
  - get
